### ISSUE TITLE
We need to add a flag field in the database and add flags for each language.

### ISSUE THREAD

**Issue by eamon0989** [alexandria-reader/backend#109]

**Comment by mrchrmn** [comment]
Should this be a DB column or be solved on the front end with a global hash object matching language IDs to icons?

**Comment by eamon0989** [comment]
I think a database column would be more futureproof right? That way if we add the option to add languages, the flag can be uploaded from the frontend? In the frontend we make an API call to get the list of languages when the app is opened, the flags could be sent along with the language objects.

**Comment by mrchrmn** [comment]
Are we talking about unicode country flag character or images? I thought unicode characters.

**Comment by eamon0989** [comment]
I hadn't thought of unicode flags, that would be better. Is there a way to auto generate them? Or do they have to be fetched from somewhere?

**Comment by mrchrmn** [comment]
I will look into this: https://en.wikipedia.org/wiki/Regional_indicator_symbol
And this: https://alanedwardes.com/blog/posts/country-code-to-flag-emoji-csharp/

**Comment by mrchrmn** [comment]
'en' is not a country code, though, but a valid abbreviation for a language.
