### ISSUE TITLE
When updating translations, properties are sent back in snake_case and the context is not being sent to the frontend

### ISSUE THREAD

**Issue by eamon0989** [alexandria-reader/backend#131]
The properties of updated translations are being sent in snake_case, they need to be converted to camelCase before being sent to the frontend.

The context is not being sent back from the server when a translation is updated.

**Comment by mrchrmn** [comment]
The context is not part of the translation. It is part of the connection between user and translation. Do you need the original context back?

**Comment by eamon0989** [comment]
If possible that would be great. Then it greatly simplifies frontend logic as I can just swap to updated translation object with the old one.

**Comment by mrchrmn** [comment]
OK, you want a `UserTranslation` object back. Got it. Slightly more complicated.

**Comment by mrchrmn** [comment]
What are you sending to the server for a translation update? A `UserTranslation`, ie. translation + potentially changed context? Or just a `Translation`? Does the context always remain the same, ie. from the first encounter?
