### ISSUE TITLE
@types/dotenv not necessary as a dev dependencies

### ISSUE THREAD

**Issue by medic-code** [alexandria-reader/backend#150]
Currently when installing the dependencies @types/dotenv is included. When running `npm install` 

`npm WARN deprecated @types/dotenv@8.2.0: This is a stub types definition. dotenv provides its own type definitions, so you do not need this installed.` 

Appears. 

Happy to make changes locally and submit PR if that's okay.

**Comment by eamon0989** [comment]
That would be great, just request a review once it's ready. Thanks for contributing!

**Comment by medic-code** [comment]
I've created a new PR for this just FYI.
