### ISSUE TITLE
For consistency, should `words.updateStatus` return the updated word rather than just the status?

### ISSUE THREAD

**Issue by eamon0989** [alexandria-reader/backend#88]

**Comment by mrchrmn** [comment]
Depends on what you want to do with it. Updating the status is a small operation on a connection table. There is no full word object involved, so I wouldn't return one. You can check whether the returned status is the one you sent and that's basically it.

**Comment by mrchrmn** [comment]
I have thought long about this when I wrote the service and that was my conclusion.

**Comment by mrchrmn** [comment]
Also, returning a full user word from this route / service would involve two more database requests.
